---
- name: "Build app"
  vars:
   dist_path: ".dist"
   app_dir: ".."
  hosts: all
  vars_files:
    - ./vars/server_addresses/_default.yml
    - ./vars/server_addresses/{{ lookup('env','ENV') }}.yml
    - ./vars/main.yml
  roles:
    - build_app
