---
  - name: install meteor npm modules
    sudo: yes
    npm: name={{ item }} global=yes state=present
    with_items:
      - forever

  - shell: "which meteor -s"
    register: meteor_result
    failed_when: False
    changed_when: meteor_result.rc != 0

  - name: install meteor
    shell: curl https://install.meteor.com | /bin/sh
    when: meteor_result.rc != 0
